/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoleRouteImport } from './routes/role'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppExpressRouteImport } from './routes/app.express'
import { Route as AppBusinessRouteImport } from './routes/app.business'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppProfessionalIdRouteImport } from './routes/app.professional.$id'

const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppExpressRoute = AppExpressRouteImport.update({
  id: '/express',
  path: '/express',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfessionalIdRoute = AppProfessionalIdRouteImport.update({
  id: '/professional/$id',
  path: '/professional/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/role': typeof RoleRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/business': typeof AppBusinessRoute
  '/app/express': typeof AppExpressRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/search': typeof AppSearchRoute
  '/p/$slug': typeof PSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/professional/$id': typeof AppProfessionalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/role': typeof RoleRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/business': typeof AppBusinessRoute
  '/app/express': typeof AppExpressRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/search': typeof AppSearchRoute
  '/p/$slug': typeof PSlugRoute
  '/app': typeof AppIndexRoute
  '/app/professional/$id': typeof AppProfessionalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/role': typeof RoleRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/business': typeof AppBusinessRoute
  '/app/express': typeof AppExpressRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/search': typeof AppSearchRoute
  '/p/$slug': typeof PSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/professional/$id': typeof AppProfessionalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/role'
    | '/app/admin'
    | '/app/agenda'
    | '/app/business'
    | '/app/express'
    | '/app/favorites'
    | '/app/messages'
    | '/app/profile'
    | '/app/requests'
    | '/app/search'
    | '/p/$slug'
    | '/app/'
    | '/app/professional/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/role'
    | '/app/admin'
    | '/app/agenda'
    | '/app/business'
    | '/app/express'
    | '/app/favorites'
    | '/app/messages'
    | '/app/profile'
    | '/app/requests'
    | '/app/search'
    | '/p/$slug'
    | '/app'
    | '/app/professional/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/role'
    | '/app/admin'
    | '/app/agenda'
    | '/app/business'
    | '/app/express'
    | '/app/favorites'
    | '/app/messages'
    | '/app/profile'
    | '/app/requests'
    | '/app/search'
    | '/p/$slug'
    | '/app/'
    | '/app/professional/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  RoleRoute: typeof RoleRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/express': {
      id: '/app/express'
      path: '/express'
      fullPath: '/app/express'
      preLoaderRoute: typeof AppExpressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/business': {
      id: '/app/business'
      path: '/business'
      fullPath: '/app/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/professional/$id': {
      id: '/app/professional/$id'
      path: '/professional/$id'
      fullPath: '/app/professional/$id'
      preLoaderRoute: typeof AppProfessionalIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppExpressRoute: typeof AppExpressRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProfessionalIdRoute: typeof AppProfessionalIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppExpressRoute: AppExpressRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppProfessionalIdRoute: AppProfessionalIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  RoleRoute: RoleRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
